# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_content',
            field=models.FileField(null=True, upload_to='photo/content_img'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_style',
            field=models.FileField(null=True, upload_to='photo/style_img'),
        ),
    ]
