# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20171120_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='result_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
